### ISSUE TITLE
Caching fails

### ISSUE THREAD

**Issue by Marius1311** [michalk8/scachepy#22]
When I try caching the output of `recover_dynamics`, I get
```
No cache found in `recover_dynamics_day12.5.pickle`, computing values.
recovering dynamics
    finished (0:10:31) --> added 
    'fit_pars', fitted parameters for splicing dynamics (adata.var)
Traceback (most recent call last):
  File "/Users/marius/Projects/scachepy/scachepy/modules.py", line 105, in wrapper
    possible_vals = set(args) | set(kwargs.values())
TypeError: unhashable type: 'AnnData'

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-39-2e43d729d3ba> in <module>
      1 #scv.tl.recover_dynamics(adata)
----> 2 c.tl.recover_dynamics(adata, fname='recover_dynamics_day{}'.format(t_point))

~/Projects/scachepy/scachepy/utils.py in __call__(self, *args, **kwargs)
    107 
    108     def __call__(self, *args, **kwargs):
--> 109         return self._fn(*args, **kwargs)
    110 
    111     def __repr__(self):

~/Projects/scachepy/scachepy/modules.py in wrapper(*args, **kwargs)
    263                 res = callback(*args, **kwargs) if call else adata if copy else None
    264                 ret = cache_fn(res if copy else adata, fname, True, False, skip, keyhint, *args, **kwargs)
--> 265                 assert ret, 'Caching failed, horribly.'
    266 
    267                 if is_plot:

AssertionError: Caching failed, horribly.

> /Users/marius/Projects/scachepy/scachepy/modules.py(265)wrapper()
    263                 res = callback(*args, **kwargs) if call else adata if copy else None
    264                 ret = cache_fn(res if copy else adata, fname, True, False, skip, keyhint, *args, **kwargs)
--> 265                 assert ret, 'Caching failed, horribly.'
    266 
    267                 if is_plot:
```
Could this be a problem with the file name? Or maybe with the anndata version? I'm using version 0.7rc3.dev5+ge499f91 from github

**Comment by michalk8** [comment]
It shouldn't be any of these problems. For some reason, it tries to hash the `adata` object, and it shouldn't
Can you show me how you call the function?

**Comment by michalk8** [comment]
Do you have the newest version? I can't seem to have find this piece `possible_vals = set(args) | set(kwargs.values())` on master and I remember removing it.

**Comment by Marius1311** [comment]
`c.tl.recover_dynamics(adata, fname='recover_dynamics_day{}'.format(t_point))`

**Comment by Marius1311** [comment]
> Do you have the newest version? I can't seem to have find this piece `possible_vals = set(args) | set(kwargs.values())` on master and I remember removing it.

Oh, no, I didn't! Sorry, my mistake. I will try again and get back to you.

**Comment by Marius1311** [comment]
Different error after pulling from master:
I call via
```python
import scachepy 
c = scachepy.Cache(os.path.join(file_paths['cache_dir'], 'pancreas'),  separate_dirs=True)
```
and I get:

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-defc49055363> in <module>
      7 
      8 # set up cache
----> 9 import scachepy
     10 c = scachepy.Cache(os.path.join(file_paths['cache_dir'], 'pancreas'),  separate_dirs=True)
     11 c

~/Projects/scachepy/scachepy/__init__.py in <module>
----> 1 from .cache import Cache

~/Projects/scachepy/scachepy/cache.py in <module>
----> 1 from .modules import PpModule, TlModule, PlModule
      2 from .backends import PickleBackend
      3 from .utils import *
      4 from pathlib import Path
      5 

~/Projects/scachepy/scachepy/modules.py in <module>
----> 1 from .backends import Backend, PickleBackend
      2 from .utils import *
      3 from collections import Iterable
      4 from abc import ABC
      5 from inspect import signature

~/Projects/scachepy/scachepy/backends.py in <module>
      6 import os
      7 import re
----> 8 import compress_pickle as cpickle
      9 import warnings
     10 

ModuleNotFoundError: No module named 'compress_pickle'
```

**Comment by Marius1311** [comment]
Okay, but that's solved after pip installing `compress_pickle`, which is actually in the requirements.

**Comment by Marius1311** [comment]
The original error is solved after pulling from master. Caching `recover_dynamics` works again!

**Comment by Marius1311** [comment]
I get a similar error now - this time I made sure I have the current github version. I call
```pyton
c = scachepy.Cache(os.path.join(file_paths['cache_dir'], 'pancreas'), backend='pickle', separate_dirs=True)
c.tl.recover_dynamics(adata)
```
 and I get the error
```python
Loading data from: `recover_dynamics.pickle`.
No cache found in `recover_dynamics.pickle`, computing values.
recovering dynamics
    finished (0:10:42) --> added 
    'fit_pars', fitted parameters for splicing dynamics (adata.var)
Traceback (most recent call last):
  File "/Users/marius/Projects/scachepy/scachepy/modules.py", line 105, in wrapper
TypeError: unhashable type: 'AnnData'

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-37-9bfb3552e21d> in <module>
      7 file_paths = get_paths()
      8 c = scachepy.Cache(os.path.join(file_paths['cache_dir'], 'pancreas'), backend='pickle', separate_dirs=True)
----> 9 c.tl.recover_dynamics(adata)
     10 
     11 #scv.tl.recover_dynamics(adata)

~/Projects/scachepy/scachepy/utils.py in __call__(self, *args, **kwargs)
    107 
    108     def __call__(self, *args, **kwargs):
--> 109         return self._fn(*args, **kwargs)
    110 
    111     def __repr__(self):

~/Projects/scachepy/scachepy/modules.py in wrapper(*args, **kwargs)
    263 
    264             # forcing always forces the callback
--> 265             if (call or force) and callback is None:
    266                 if default_fn is None:
    267                     raise RuntimeError('No callback specified and default is None; specify it as a 1st argument. ')

AssertionError: Caching failed, horribly.
```
I don't understand why, in the first place, we have to recompute the values, since I cached this before, and scachepy seems to even find the file!

**Comment by Marius1311** [comment]
Wow, but I really likes that it shows the underlying docstring now, that's amazing!

**Comment by michalk8** [comment]
@Marius1311 this is very strange because of the following line:
```python
File "/Users/marius/Projects/scachepy/scachepy/modules.py", line 105, in wrapper
```
When I look at GH (or my src files, line 105) in `modules.py`, the line is empty. Are you sure you had the correct environment? Because it works for me - I'd check the file above and see, because on GH there's nothing https://github.com/theislab/scachepy/blob/master/scachepy/modules.py#L105.

**Comment by Marius1311** [comment]
I see - okay, maybe there is a mistake on my part, let me check

**Comment by michalk8** [comment]
Assuming this has been fixed. If not, feel free to repone.

**Comment by Marius1311** [comment]
thanks!
